
spring:
  rabbitmq:
    host: 47.116.177.56
    port: 5672
    username: guest
    password: guest
    connection-timeout: 200ms # MQ连接超时时间
    template: # template就是生产者端的配置
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后的下次等待时长倍数，下次等待时间 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
    publisher-returns: true
    publisher-confirm-type: correlated
    listener: # listener就是消费者端的配置
      simple:
        prefetch: 1 # 消费者每次只预取一条消息处理 正常都是配 1
        acknowledge-mode: auto # 确认机制的类型
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初始的失败等待时长
          multiplier: 1 # 下次等待时长的倍数 下次等待时间 = initial-interval * multiplier
          max-attempts: 3 # 最大重试次数
          stateless: true # true 无状态 false 有状态，如果业务中存在事务，则这里改为false
    virtual-host: blog
