
spring:
  rabbitmq:
    host: 47.116.177.56
    port: 5672
    username: guest
    password: guest
    connection-timeout: 200ms # MQ连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后的下次等待时长倍数，下次等待时间 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
    publisher-returns: true
    publisher-confirm-type: correlated